export { default as AboutUs } from './AboutUs';
export { default as Chef } from './Chef';
export { default as FindUs } from './Findus';
export { default as Footer } from './Footer';
export { default as Gallery } from './Gallery';
export { default as Header } from './Header';
export { default as Intro } from './Intro';
export { default as Laurels } from './Laurels';
export { default as SpecialMenu } from './Menu';
